import './globals.css'
import "primeicons/primeicons.css"
import { Inter,Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppinsLight = Poppins({weight:"300",variable:"--poppinsLight",subsets: ['latin']})
const poppinsMedium = Poppins({weight:"400",variable:"--poppinsMedium",subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppinsLight.className}>{children}</body>
    </html>
  )
}
